name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm ci

      - name: Instalar navegadores do Playwright
        run: npx playwright install --with-deps chromium

      - name: Buildar a extensão
        run: npm run build

      - name: Rodar testes E2E
        run: npm run test

      - name: Publicar relatório do Playwright
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/

      - name: Publicar pacote da extensão
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: extension-dist
          path: dist/