name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'Bootcamp Project'
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # NOVO PASSO DE DEBUG
      - name: Listar arquivos no diretório
        run: ls -la

      - name: Buildar a extensão
        run: npm run build

      - name: Rodar testes E2E
        run: npm run test

      - name: Publicar relatório do Playwright
        uses: actions/upload-artifact@v4
        if: always() # Garante que o relatório seja salvo mesmo se os testes falharem
        with:
          name: playwright-report
          path: 'Bootcamp Project/playwright-report' # <--- Adicionei o caminho aqui

      - name: Publicar pacote da extensão
        uses: actions/upload-artifact@v4
        with:
          name: extension-dist
          path: 'Bootcamp Project/dist' # <--- E aqui também